### PR TITLE
20 Add test github action

### LINKED ISSUE #20: Add cross compilation for spark 3
## Background
Add cross compilation for spark 3

### PR DESCRIPTION
**Pull request by Zejnilovic**
Fixes #20

### CODE REVIEW

**Comment by Zejnilovic** [comment]
@yruslan please tell me if you want a job per file or parallel jobs in one file

**Comment by yruslan** [comment]
I used 3 separate files in Cobrix so that it would be possible to add 3 badges.
But now I'm thinking why we want 3 badges in the first place. Badges in Cobrix have render issues (last digit is cut).
Will think about it until tomorrow...

**Review by yruslan — APPROVED** [review]
Fantastic!

**Comment by Zejnilovic** [comment]
> I used 3 separate files in Cobrix so that it would be possible to add 3 badges.
> But now I'm thinking why we want 3 badges in the first place. Badges in Cobrix have render issues (last digit is cut).
> Will think about it until tomorrow...

One more thing to think about. I saw that in Cobrix you don't use setup `olafurpg/setup-scala@v10` but just plain java. I am surprised it knows about `sbt`.

BTW opened an (issue)[https://github.com/olafurpg/setup-scala/issues/33] in olafurpg/setup-scala for speeding up of SBT setup. Let's see what happens.

**Comment by yruslan** [comment]
To be honest I just followed GitHub wizard to create the initial Cobrix build workflow file. I was also surprised that sbt was there. 

I like the idea of [#33 - Speeding up sbt](https://github.com/olafurpg/setup-scala/issues/33). Will copycat it to Cobrix 😄

**Pull request merged**
